# Generated by Django 3.1.5 on 2021-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='comments',
            field=models.CharField(default='1', max_length=300),
        ),
    ]
