# Generated by Django 3.1.5 on 2021-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_auto_20210228_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='comments',
            field=models.CharField(max_length=300),
        ),
    ]
